MNT Standardise modules
kinglozzer/silverstripe-session-manager pull request #117
Opened 2022-07-31 22:43 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/570

2022-08-01 03:13 UTC, GuySartorelli commented
At least one CI job failed here

2022-08-01 05:01 UTC, emteknetnz commented
Fixed

2022-08-02 03:23 UTC, GuySartorelli requested changes

2022-08-02 03:23 UTC, GuySartorelli commented on README.md
> -![CMS view](images/cms.png)
Why remove this?

2022-08-02 05:35 UTC, emteknetnz commented on README.md
> -![CMS view](images/cms.png)
Added back in

2022-08-02 22:04 UTC, GuySartorelli approved these changes

2022-08-02 22:04 UTC, merged