Garbage collector do not work on large tables
kinglozzer/silverstripe-session-manager pull request #163
Opened 2023-08-10 08:53 UTC by lekoala

Fixes https://github.com/silverstripe/silverstripe-session-manager/issues/153

2023-08-10 21:12 UTC, GuySartorelli requested changes
Sorry, I didn't realise in your code sample in the issue that this would change the return type for some methods - we can't change return type as that will require anyone who has subclassed this class and overridden those methods to change their method signatures as well.

That said, given that the idea here is just to get the thing to _work_, I'd still be okay with the change from `removeAll()` to `batchRemoveAll()` without the API and output changes

2023-08-10 21:12 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +    public function collect(): array
```suggestion
    public function collect(): void
```

2023-08-10 21:12 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +        ];
```suggestion
        $this->collectExpiredSessions();
        $this->collectImplicitlyExpiredSessions();
        $this->collectExpiredLoginHashes();
```

2023-08-10 21:12 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +        $sessions = LoginSession::get()->filter([
```suggestion
        LoginSession::get()->filter([
```

2023-08-10 21:12 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +        return $this->batchRemoveAll($sessions);
```suggestion
        $this->batchRemoveAll($sessions);
```

2023-08-10 21:12 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +        return $this->batchRemoveAll($sessions);
```suggestion
        $this->batchRemoveAll($sessions);
```

2023-08-10 21:12 UTC, ChloeSartorelli commented on src/Services/GarbageCollectionService.php
> +        return $i;
```suggestion
    private function batchRemoveAll($datalist)
    {
        $limit = self::config()->get('batch_remove_limit');
        $limitedList = $limit > 0 ? $datalist->limit($limit) : $datalist;
        DB::get_conn()->transactionStart();
        foreach ($limitedList as $record) {
            $record->delete();
        }
        DB::get_conn()->transactionEnd();
```

2023-08-10 21:12 UTC, ChloeSartorelli commented on src/Services/GarbageCollectionService.php
> +        $hashes = RememberLoginHash::get()->filter([
```suggestion
        RememberLoginHash::get()->filter([
```

2023-08-10 21:12 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +        return $this->batchRemoveAll($hashes);
```suggestion
```

2023-08-10 21:12 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +    private static int $batch_remove_limit = 0;
```suggestion
     * Limit the number of records collected per run. Defaults to null (no limit).
     */
    private static ?int $batch_remove_limit = null;
```

2023-08-10 21:12 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +        $limitedList = $limit > 0 ? $datalist->limit($limit) : $datalist;
```suggestion
        $limit = self::config()->get('batch_remove_limit');
        $limitedList = $datalist->limit($limit);
```
With the default limit set to null, we can just trust the limit value outright.

2023-08-11 07:45 UTC, lekoala commented
no worries, the change for the collect method was an added benefit. and instead of changing the return type, it's possible to store the result somewhere and add a getResults but that can be another PR. I still think it's valuable to allow to have some insights on what's being collected
For example in my cron tasks module, I store tasks results in the database. This would allow to know when you hit the limit, if you run this frequently enough, etc.

I've merged your changes and fixed some vars that went missing along the way

2023-08-14 00:24 UTC, GuySartorelli requested changes
Looks good, can't see any issues with this now. Please resolve the conflict and I'll be happy to merge.

2023-08-14 00:24 UTC, GuySartorelli commented on src/Services/GarbageCollectionService.php
> +use SilverStripe\ORM\FieldType\DBDatetime;
```suggestion
```
I was going to ignore this but you need to resolve merge conflicts anyway so may as well remove this unnecessary statement at the same time.

2023-08-14 22:15 UTC, GuySartorelli commented
@lekoala Can you please resolve the merge conflict?

2023-08-15 20:55 UTC, GuySartorelli approved these changes
Thanks, looks good and works as expected.

2023-08-15 20:55 UTC, merged