MNT Remove module documentation
kinglozzer/silverstripe-session-manager pull request #164
Opened 2023-08-14 05:15 UTC by emteknetnz

Issue https://github.com/silverstripe/developer-docs/issues/322

2023-08-14 23:46 UTC, GuySartorelli requested changes
I think cms.png is more outdated than erroneous - but either way it's not used so I'm fine with its removal.
Just one tiny change to make please.

2023-08-14 23:46 UTC, GuySartorelli commented on README.md
> +See [Managing Sessions](https://docs.silverstripe.org/en/5/developer_guides/cookies_and_sessions/cookies/) on [docs.silverstripe.org](https://docs.silverstripe.org).
```suggestion
See [Managing Sessions](https://docs.silverstripe.org/en/developer_guides/cookies_and_sessions/cookies/) on [docs.silverstripe.org](https://docs.silverstripe.org).
```

2023-08-15 03:57 UTC, emteknetnz commented on README.md
> +See [Managing Sessions](https://docs.silverstripe.org/en/5/developer_guides/cookies_and_sessions/cookies/) on [docs.silverstripe.org](https://docs.silverstripe.org).
Updated

2023-08-15 04:08 UTC, GuySartorelli approved these changes

2023-08-15 04:09 UTC, merged