Scaffold react components
kinglozzer/silverstripe-session-manager pull request #21
Opened 2021-02-22 06:15 UTC by bergice

2021-02-23 22:24 UTC, Cheddam requested changes
A few bits to trim and rename, otherwise this is a solid base to build on 👍

2021-02-23 22:24 UTC, Cheddam commented on CONTRIBUTING.md
> +of that code to MODULE_COPYRIGHT_HOLDER_HERE., on the condition that these code changes are released under the
```suggestion
of that code to Silverstripe Ltd., on the condition that these code changes are released under the 
```

2021-02-23 22:24 UTC, Cheddam commented on src/Extensions/MemberExtension.php
> +            $methodListField = SessionManagerField::create(
I think this is leftover naming from MFA?

```suggestion
            $sessionManagerField = SessionManagerField::create(
```

2021-02-23 22:24 UTC, Cheddam commented on src/Extensions/MemberExtension.php
> +    public function currentUserCanViewSessionManagerConfig(): bool
```suggestion
    public function currentUserCanViewSessionsForMember(): bool
```

2021-02-23 22:24 UTC, Cheddam commented on src/Extensions/MemberExtension.php
> +    public function currentUserCanEditSessionManagerConfig(): bool
```suggestion
    public function currentUserCanEditSessionsForMember(): bool
```

2021-02-23 22:24 UTC, Cheddam commented on src/Extensions/MemberExtension.php
> +            'Ability to view and reset registered SessionManager methods for other members.'
```suggestion
            'Ability to view and purge active login sessions for other members.'
```

2021-02-23 22:24 UTC, Cheddam commented on src/Extensions/MemberExtension.php
> +            'View/reset SessionManager configuration for other members'
```suggestion
            'View/purge login sessions for other members'
```

2021-02-23 22:24 UTC, Cheddam commented on src/FormField/SessionManagerField.php
> +    }
This is definitely left over from MFA 😅 

```suggestion

```

2021-02-23 22:24 UTC, Cheddam commented on client/src/bundles/bundle.scss
> +// e.g. @import '../components/MyComponent/MyComponent.scss';
Could scaffold SessionManagerField.scss as part of this PR?

2021-02-23 22:24 UTC, Cheddam commented on src/Extensions/MemberExtension.php
> +use SilverStripe\MFA\Model\RegisteredMethod;
```suggestion
```

2021-02-25 03:33 UTC, bergice commented on src/FormField/SessionManagerField.php
> +    }
Hehe, oopsie.

2021-02-25 03:56 UTC, bergice commented
> A few bits to trim and rename, otherwise this is a solid base to build on 👍

@Cheddam I've fixed up the things you requested. :)

2021-03-01 02:21 UTC, Cheddam approved these changes

2021-03-08 00:23 UTC, merged