API Set default value of framework RememberLoginHash logout_across_devices to false
kinglozzer/silverstripe-session-manager pull request #66
Opened 2021-04-21 02:34 UTC by emteknetnz

Issue: https://github.com/silverstripe/silverstripe-session-manager/issues/65

2021-04-21 22:09 UTC, maxime-rainville commented on README.md
> +This module will update the `SilverStripe\Security\RememberLoginHash.logout_across_devices` config setting, setting it to `false` by default.
```suggestion
This module updates the `SilverStripe\Security\RememberLoginHash.logout_across_devices` configuration flag to default to `false`.
```

2021-04-21 22:21 UTC, emteknetnz commented on README.md
> +This module will update the `SilverStripe\Security\RememberLoginHash.logout_across_devices` config setting, setting it to `false` by default.
Have updated text

2021-04-21 23:16 UTC, maxime-rainville requested changes
Looks good ... tested the new behaviour with and without the code snippet in the doc.

My instinct would be to keep the doc a bit more simple, but I don't have strong feelings about it.

2021-04-21 23:16 UTC, maxime-rainville commented on README.md
> +To restore the old behaviour with session manager installed, add the following YML config to your project:
I don't think we need to go into this level of detail here.

There's a already a [bit about this config flag in the regular doc](https://docs.silverstripe.org/en/4/developer_guides/security/member/#saved-user-logins). If this does not provide enough info, then it probably make more sense to update it there.

I would be tempted to keep it short and sweet. Maybe something like:
> Session-manager provides an explicit way to terminate individual sessions and their attached "remember me" tokens. So this module sets `SilverStripe\Security\RememberLoginHash.logout_across_devices` to `false`.
>
> To restore the old behaviour with session manager installed, add the following YML config to your project:
> ...
> Read [Saved User Logins](https://docs.silverstripe.org/en/4/developer_guides/security/member/#saved-user-logins) to learn how to configure the "remember me" feature for your users.

2021-04-22 01:59 UTC, emteknetnz commented on README.md
> +To restore the old behaviour with session manager installed, add the following YML config to your project:
Updated to your text

2021-04-22 04:47 UTC, maxime-rainville approved these changes

2021-04-22 04:48 UTC, merged