ENH Update folders + namespaces, remove unused class
kinglozzer/silverstripe-session-manager pull request #74
Opened 2021-06-09 00:40 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-session-manager/issues/42

2021-06-09 21:42 UTC, bergice requested changes
Causes a fatal error if there are `LoginSessions` existing already before applying this as it's processing them in the middleware: `[Emergency] Uncaught SilverStripe\ORM\ValidationException: Object is of class 'SilverStripe\SessionManager\Model\LoginSession' which doesn't exist - you need to change the ClassName before you can write it`.
Might be okay if no one is using the module yet.

After removing `LoginSessions` from the database, I'm getting this error: `[Emergency] Uncaught Error: Call to undefined method SilverStripe\Security\RememberLoginHash::setLogoutAcrossDevices()`. Not sure why this method is gone.
Seems like it should now be `RememberLoginHash::config()->update('logout_across_devices', false);`

2021-06-10 01:20 UTC, emteknetnz commented
@bergice you probably need to run `composer update` - basically you want to be runing 4.8 on your local - there was new API added to framework and the requiremnts withing session-manager was bumped to `"silverstripe/framework": "^4.8",`

2021-06-10 01:58 UTC, merged

2021-06-11 05:03 UTC, maxime-rainville commented on src/Controllers/LoginSessionController.php
> +class LoginSessionController extends Controller
@emteknetnz @bergice Changing this class from `LeftAndMain` to `Controller` completely nukes the functionality. I understand this is a big PR, but you should at least try to run these things before merging them.

2021-06-11 05:04 UTC, maxime-rainville commented on src/Controllers/LoginSessionController.php
> +class LoginSessionController extends Controller
I'll fix it through https://github.com/silverstripe/silverstripe-session-manager/issues/67

2021-06-11 05:15 UTC, maxime-rainville commented on src/Controllers/LoginSessionController.php
> +class LoginSessionController extends Controller
Sorry, it was my screw up. I change something else on my set up ... just ignore me.