ENH Remove logout confirmation
kinglozzer/silverstripe-session-manager pull request #80
Opened 2021-06-16 00:55 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-session-manager/issues/79

2021-06-16 02:11 UTC, brynwhyman commented
Looks like there's a behat test still expecting to see the modal, failing.

2021-06-18 05:05 UTC, maxime-rainville requested changes
Works great ... left a few minor suggestion.

2021-06-18 05:05 UTC, maxime-rainville commented on client/lang/src/en.json
>    "SessionManager.CONFIRMATION_TITLE": "Are you sure?",
Is this translation still needed?

2021-06-18 05:05 UTC, maxime-rainville commented on lang/en.yml
> +    DEVICES: 'Authenticated devices'
Didn't we update this to say "session". Did I screw something up while rebasing on top https://github.com/silverstripe/silverstripe-session-manager/pull/71 ?

2021-06-18 05:05 UTC, maxime-rainville commented on client/src/components/LoginSession/LoginSession.js
> +  function attemptLogOut() {
Very minor quibble, but it might make more sense at this stage to conditionally attach the `logout` function to the button at this stage.

2021-06-18 05:05 UTC, maxime-rainville commented on lang/en.yml
> +    DEVICES: 'Authenticated devices'
I know I said "No removing translation keys", but I thought you were talking about a supported module. In the context of a translation key that never was release in a stable version, I think it's fine to remove them if they turn out to not be needed.

2021-06-20 22:16 UTC, emteknetnz commented on client/lang/src/en.json
>    "SessionManager.CONFIRMATION_TITLE": "Are you sure?",
Removed

2021-06-20 22:20 UTC, emteknetnz commented on client/src/components/LoginSession/LoginSession.js
> +  function attemptLogOut() {
If it's very minor then it's probably not worth refactoring

2021-06-20 22:22 UTC, emteknetnz commented on lang/en.yml
> +    DEVICES: 'Authenticated devices'
May have been a messy rebase - I've updated to reference what was done in https://github.com/silverstripe/silverstripe-session-manager/pull/71/files

2021-06-20 23:58 UTC, maxime-rainville approved these changes

2021-06-20 23:59 UTC, merged