DOC Move userhelp to silverstirpe-userhelp-content
kinglozzer/silverstripe-session-manager pull request #86
Opened 2021-08-04 23:31 UTC by emteknetnz

Issue https://github.com/silverstripe/recipe-cms/issues/47

2021-08-09 05:29 UTC, maxime-rainville approved these changes, later dismissed

2021-08-09 05:31 UTC, maxime-rainville requested changes
Won't moving this doc somewhere else change the URL of the doc? There's a few places where we reference the user help in the module. Those should be updated as well.

2021-08-11 23:53 UTC, emteknetnz commented
Good spot.  Just a single reference which I've updated

2021-08-12 22:49 UTC, maxime-rainville approved these changes

2021-08-12 23:00 UTC, merged